// <auto-generated />
namespace EvCoSample.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_StoredEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_StoredEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201508201322158_Added_StoredEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
